feat: 内部仕様のドキュメントを自動生成できるようにした
pulsate-dev/specification pull request #14
Opened 2024-08-26 11:39 UTC by laminne

## 概要
close #13 

- `deno doc`を利用してドキュメントを生成するスクリプトの実装
- 生成されたドキュメントの追加

2024-08-26 12:07 UTC, MikuroXina reviewed
これらの HTML ファイルはプレーンテキストをそのまま読むには適さなそうですが, これらは main ブランチに載せるのではなく GitHub Pages にデプロイするのでしょうか? それともそのままこれらの HTML ファイルをバージョン管理する方針なのでしょうか?

2024-08-26 12:08 UTC, laminne commented
HTMLのドキュメントはデプロイする前提で考えています

2024-08-26 12:10 UTC, laminne commented
これらのドキュメントをバージョン管理するのは意味がなさそうなので、CI等で自動生成してデプロイする感じにした方が良さそう

2024-08-26 12:15 UTC, m1sk9 requested changes
ちょっと待って. これらの大量の HTML をリポジトリに残すつもりですか?
流石に Git で管理する量ではないです. これらは本来人間が `deno doc` など適切なコマンドを実行して生成してその場で確認すべきものであり, リポジトリに残すべきではないです.
プルリクエストのレビュー画面が固まって操作不能になるほどなのでもし公開したいのであれば Deno Deploy などを使うべきです...

2024-08-29 14:09 UTC, m1sk9 approved these changes
spec に残しておくことについてはもう少し話しておく必要がありそうですが, とりあえず Approve します

2024-08-29 14:09 UTC, merged