feat: notification apis specification
pulsate-dev/specification pull request #16
Opened 2024-08-29 12:58 UTC by laminne

## 概要
- 通知APIのドキュメントを書きました

### ToDos
- モデレーション関連の通知種類の定義

2024-08-29 13:18 UTC, MikuroXina requested changes

2024-08-29 13:18 UTC, MikuroXina commented on src/endpoint/notification.md
> +##### `followed` - フォローされた
```suggestion
## お知らせ（Announce)の種類

| 種類コード |         説明         |
| :--------: | :------------------: |
|   `info`   |   一般的なお知らせ   |
|   `warn`   | ユーザー全体への警告 |

## 通知の種類 / `actor`の種類

通知の種類

## `followed` - フォローされた
```
見出しレベルはこのように段階を飛ばさず階層的にしてほしいです.

2024-08-29 14:47 UTC, MikuroXina requested changes

2024-08-29 14:47 UTC, MikuroXina commented on src/endpoint/notification.md
> +通知の種類
このテキストは見出しと同じになっていて意味が無いので, 通知の種類, 意味論, その通知が起こり得る状況についての説明があったほうがよさそうです.

2024-08-29 14:47 UTC, MikuroXina commented on src/endpoint/notification.md
> +## `followed` - フォローされた
```suggestion
### `followed` - フォローされた
```
先ほど Request change をしていましたが, もしかしてこれらの種類の説明はこのように「通知の種類 / `actor`の種類」の下のつもりだったでしょうか?

2024-08-29 14:47 UTC, MikuroXina commented on src/endpoint/notification.md
> +届いているすべての通知を取得します。すでに既読がついている通知は表示されません。
一度既読にすると, 過去の通知はもう取得できないのでしょうか? クエリパラメータで既読も取得するようにしたり, 一定期間内の通知を取得できるようなクエリパラメータを追加したりするのは検討しましたか?

2024-08-30 00:24 UTC, laminne commented on src/endpoint/notification.md
> +届いているすべての通知を取得します。すでに既読がついている通知は表示されません。
クエリパラメータを追加しました ([47e4401](https://github.com/pulsate-dev/specification/pull/16/commits/47e4401f42b1903de4a7888c3cca72720e9459f3) )

2024-08-30 03:16 UTC, MikuroXina requested changes

2024-08-30 03:16 UTC, MikuroXina commented on src/endpoint/notification.md
> +      "avatar": "https://cdn.example.com/johndoe/avater"
```suggestion
      "avatar": "https://cdn.example.com/johndoe/avatar"
```
1 つ修正していましたが, 同様の typo がここも含めて他にもまだ残っています

2024-08-30 10:28 UTC, MikuroXina commented on src/endpoint/notification.md
> +    // ToDo
ここが ToDo になっていますが, 通知 API の仕様策定についての Issue #15 にて後からこの議論が必要である旨を書いたほうがよさそうです.

2024-08-30 11:41 UTC, laminne commented on src/endpoint/notification.md
> +    // ToDo
done

2024-08-30 11:42 UTC, MikuroXina approved these changes

2024-08-30 11:42 UTC, merged